classDiagram
    class Hierarchy {
        +Guid Id
        +HierarchyType Type
        +string Parent
        +string Child
    }
    class Relation {
        +Guid Id
        +string Name
        +int Arity
        +List~string~ Signature
    }
