flowchart TD
    subgraph Page [KBMS.Storage.Core.SlottedPage - 16KB]
        direction TB
        Header[Header 24 bytes: PageID, LSN, PrevPageId, NextPageId, FreeSpace, TupleCount]
        Slots[Slot Array: 8 bytes per slot offset/length]
        Free[Free Space: Vùng nhớ trống phình to từ giữa]
        R2[Record 2: Byte nhị phân Tuple]
        R1[Record 1: Byte nhị phân Tuple]
        
        Header --- Slots
        Slots --- Free
        Free --- R2
        R2 --- R1
    end
