classDiagram
    class Page_16KB {
        +Header_9B
        +Data_Region_16375B
    }
    class Header_9B {
        +IsLeaf: byte
        +KeyCount: short
        +MaxKeys: short
        +ParentId: int
    }
    class Leaf_Data {
        +Key_Array
        +Object_Payloads
    }
    class Internal_Data {
        +Key_Array
        +Child_PageIds
    }
    Page_16KB *-- Header_9B
    Page_16KB *-- Leaf_Data
    Page_16KB *-- Internal_Data
