graph TD
    classDef main fill:#f9f,stroke:#333,stroke-width:2px;
    classDef sub fill:#bdf,stroke:#333,stroke-width:1px;

    subgraph "Server Layer (Storage Management)"
        SP["StoragePool (Singleton)"]:::main
    end
    
    subgraph "Storage Layer (Physical Management)"
        BPM["BufferPoolManager (LRU Cache)"]:::sub
        DM["DiskManager (16KB Blocks)"]:::sub
        WAL["WalManager (Transaction Logger)"]:::sub
        
        DATA[(".dat Physical Files")]
        LOGS[(".log WAL Files")]
    end
    
    SP --> BPM
    BPM <--> DM
    BPM <--> WAL
    DM <--> DATA
    WAL <--> LOGS
