using System.Collections.Generic;
using System.Text;

namespace KBMS.Knowledge.V3.Optimizer;

/// <summary>
/// Represents a node in the physical execution plan generated by the Cost-Based Optimizer.
/// Used primarily for the EXPLAIN command to show developers how their query will be processed.
/// </summary>
public abstract class PlanNode
{
    public string Operation { get; set; } = string.Empty;
    public string Detail { get; set; } = string.Empty;
    public double EstimatedCost { get; set; } = 0.0;
    public int EstimatedRows { get; set; } = 0;
    
    public List<PlanNode> Children { get; set; } = new();

    /// <summary>
    /// Recursively formats the execution plan into a human-readable tree string.
    /// </summary>
    public string FormatExplain(int indentLevel = 0)
    {
        var sb = new StringBuilder();
        string indent = new string(' ', indentLevel * 4);
        
        sb.AppendLine($"{indent}-> {Operation} ({Detail})");
        sb.AppendLine($"{indent}     Cost: {EstimatedCost:F2}, Rows: {EstimatedRows}");

        foreach (var child in Children)
        {
            sb.Append(child.FormatExplain(indentLevel + 1));
        }

        return sb.ToString();
    }
}

public class ScanPlanNode : PlanNode { }
public class FilterPlanNode : PlanNode { }
public class HashJoinPlanNode : PlanNode { }
public class NestedLoopJoinPlanNode : PlanNode { }
